#!/usr/bin/env python3
"""Refresh the visa_data domain-classification snapshot to post-PR #440 reality.

The original snapshot (docs/data/2026_05_21_visa_data_domain_classification.json)
classified a 58/59-record visa_data.json in which 17 scenario/help/FAQ records
still lived inside the master. PR #440-era cleanup removed those 17 from the
generated visa_data.json (they remain in data/scenario_help_records.json and are
re-added for the backend/AI path via the union resolver). The snapshot's
(array_index, code) pairs therefore no longer line up with the current
42-record file, which made check_visa_data_domain_classification.py red.

This generator produces a refreshed snapshot that reflects the current 42-record
generated visa_data.json WITHOUT inventing any classification:
  * every current record reuses its EXISTING classification (matched by code)
    from the old snapshot, with array_index updated to the current position;
  * the 17 removed records are preserved verbatim under `migrated_out_records`
    for provenance (they are no longer part of the visa_data master);
  * a current code with no prior classification is emitted as `needs_review`
    (none on this branch — reported if it ever happens).

It does NOT change any legal/eligibility/source content; classifications are
internal taxonomy metadata.

Usage:
  python3 scripts/visa/refresh_domain_classification.py [--check]
    --check  exit 1 if the on-disk refreshed snapshot is stale (no write)
"""
from __future__ import annotations

import argparse
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import _visa_pipeline_common as C  # noqa: E402

OLD = C.REPO_ROOT / "docs/data/2026_05_21_visa_data_domain_classification.json"
NEW = C.REPO_ROOT / "docs/data/2026_06_18_visa_data_domain_classification.json"

REQUIRED_FIELDS = ("array_index", "code", "primary_type", "source_grounding",
                   "keep_in_visa_data", "future_destination")


def build() -> dict:
    old = C.load_json(OLD)
    visas = C.load_json(C.VISA_DATA)
    by_code = {r["code"]: r for r in old["records"]}

    records, needs_review = [], []
    for i, rec in enumerate(visas):
        code = rec.get("code")
        prior = by_code.get(code)
        if prior is None:
            entry = {
                "array_index": i, "code": code,
                "primary_type": "unknown", "source_grounding": "unresolved",
                "keep_in_visa_data": "keep",
                "future_destination": "visa_data_master",
                "recommended_action": "needs_review",
                "_refresh_note": "no prior classification; marked needs_review",
            }
            needs_review.append(code)
        else:
            entry = dict(prior)
            entry["array_index"] = i  # reindex to current position
        records.append(entry)

    current_codes = {r["code"] for r in visas}
    migrated_out = [r for r in old["records"] if r["code"] not in current_codes]

    summary = {
        "total_records": len(records),
        "by_primary_type": dict(Counter(r["primary_type"] for r in records)),
        "by_keep_in_visa_data": dict(Counter(r["keep_in_visa_data"] for r in records)),
        "migrated_out_count": len(migrated_out),
        "needs_review": needs_review,
    }

    return {
        "schema_version": old.get("schema_version", "1.0"),
        "report": "visa_data.json domain & source-grounding classification "
                  "(refreshed for the post-PR #440 generated 42-record master)",
        "supersedes": "docs/data/2026_05_21_visa_data_domain_classification.json",
        "refreshed_from": "visa_data.json (generated) + prior snapshot, matched by code",
        "audit_date": "2026-06-18",
        "generated": True,
        "disclaimer": old.get("disclaimer",
                              "Internal audit/classification artifact. Not legal advice."),
        "taxonomy": old.get("taxonomy", {}),
        "summary": summary,
        "hard_dependencies": old.get("hard_dependencies", {}),
        "records": records,
        "migrated_out_records": migrated_out,
        "_meta": {
            "note": "GENERATED by scripts/visa/refresh_domain_classification.py. "
                    "Do not hand-edit. Records reindexed to current visa_data.json; "
                    "classifications reused by code (no legal content changed). The 17 "
                    "scenario/help records removed from the master on 2026-06-08 are "
                    "preserved under migrated_out_records for provenance.",
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    rendered = C.dump_authoring_json(build())
    if args.check:
        current = NEW.read_text(encoding="utf-8") if NEW.exists() else ""
        if rendered != current:
            print("ERROR: refreshed domain-classification snapshot is stale "
                  "(run scripts/visa/refresh_domain_classification.py)", file=sys.stderr)
            return 1
        print("OK: refreshed domain-classification snapshot is up to date.")
        return 0

    NEW.write_text(rendered, encoding="utf-8")
    print(f"Wrote {NEW.relative_to(C.REPO_ROOT)} "
          f"({len(C.load_json(NEW)['records'])} records, "
          f"{len(C.load_json(NEW)['migrated_out_records'])} migrated-out)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
