#!/usr/bin/env node
/*
 * build_landing_shell.mjs — regenerate the static civic landing shell in index.html.
 *
 * The civic landing used to exist only after `civic-search.js` ran at the end of
 * the 1.4 MB document, so every visit painted the legacy hero first. The static
 * shell below is the Korean output of the same `homeHtml()` builder that the
 * script renders, so first paint and the hydrated landing are byte-for-byte the
 * same markup: the script reuses the shell instead of re-rendering it.
 *
 *   node scripts/build_landing_shell.mjs        # rewrite index.html
 *   node scripts/check_landing_shell.mjs        # CI: assert index.html is current
 *
 * The block is delimited by the two marker comments below. Korean copy comes
 * from data/i18n/ko.json (`civic`), which check_landing_shell.mjs also asserts
 * equals the bootstrap copy inside civic-search.js.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const START = '<!-- civic landing shell: generated by scripts/build_landing_shell.mjs from assets/js/civic-search.js homeHtml(); do not edit by hand -->';
export const END = '<!-- /civic landing shell -->';

export function loadCivic() {
  // civic-search.js publishes its API and returns before touching the landing DOM
  // when #mainContent does not exist, so a two-line document stub is enough.
  const src = readFileSync(join(ROOT, 'assets/js/civic-search.js'), 'utf8');
  const sandbox = {
    document: { getElementById: () => null, documentElement: { lang: 'ko' }, readyState: 'complete', addEventListener() {}, createElement: () => ({ setAttribute() {}, querySelector: () => null }) },
    location: { href: 'http://127.0.0.1/index.html' },
    matchMedia: () => ({ matches: false })
  };
  sandbox.window = sandbox;
  const fn = new Function('window', 'document', 'location', src + '\nreturn window.VisableCivicSearch;');
  return fn(sandbox, sandbox.document, sandbox.location);
}

export function shellHtml(civic) {
  const ko = JSON.parse(readFileSync(join(ROOT, 'data/i18n/ko.json'), 'utf8')).civic || {};
  const T = (key) => (typeof ko[key] === 'string' ? ko[key] : civic.copy.ko[key]);
  return civic.homeHtml(T, { langCode: 'ko' });
}

export function renderShellBlock(civic) {
  return `${START}\n<div id="civicLanding" data-cs-shell="ko" data-cs-hydrated="static">${shellHtml(civic)}</div>\n${END}`;
}

export function replaceShell(html, block) {
  const a = html.indexOf(START), b = html.indexOf(END);
  if (a < 0 || b < 0) throw new Error('shell markers not found in index.html');
  return html.slice(0, a) + block + html.slice(b + END.length);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const file = join(ROOT, 'index.html');
  const html = readFileSync(file, 'utf8');
  const next = replaceShell(html, renderShellBlock(loadCivic()));
  if (next === html) console.log('[build_landing_shell] index.html already current');
  else { writeFileSync(file, next); console.log('[build_landing_shell] index.html shell regenerated'); }
}
