#!/usr/bin/env node
/*
 * check_popup_i18n.mjs — regression guard for popup/modal UI i18n in the
 * standalone guide modules (assets/js/*.js). These render popup chrome from
 * Korean-canonical string packs that must have a matching English pack so the
 * popup never shows untranslated Korean chrome in English mode.
 *
 * What it checks (chrome only — NOT legal/source data content):
 *   1. Each module's KO chrome pack (STR_KO / TAB_LABEL_KO) has a 1:1 key match
 *      with its EN pack (STR_EN / TAB_LABEL_EN) — no key drifts untranslated.
 *   2. Every <select> option object carries a labelEn alongside its Korean label.
 *   3. No hardcoded Korean inside HTML attribute literals (aria-label / title /
 *      placeholder) — those must come from a language-aware pack.
 *
 * Deliberately NOT flagged: Korean inside the result-body eligibility phrasing
 * generated by short-stay-checker.js (computeShortStay) and Korean data fetched
 * from data/**.json. That content is legal/source material kept Korean-canonical
 * per the project i18n policy (data/i18n/manifest.json) and is out of scope for
 * a chrome-only popup translation pass.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');

const KO = /[가-힣]/;
const problems = [];
function fail(file, msg) { problems.push(`${file}: ${msg}`); }

// Extract the top-level identifier keys declared in `var NAME = { ... };`.
// Walks char-by-char, skipping string/template literals, so colons inside
// values (e.g. "metadata: data/...") are never mistaken for object keys.
function packKeys(src, name) {
  const decl = 'var ' + name + ' = {';
  const start = src.indexOf(decl);
  if (start === -1) return null;
  let i = src.indexOf('{', start) + 1;
  const keys = new Set();
  let depth = 0;          // nesting depth relative to the pack body
  let pendingIdent = '';  // last identifier seen at depth 0
  while (i < src.length) {
    const ch = src[i];
    if (ch === '"' || ch === "'" || ch === '`') {
      // skip the whole string literal
      const q = ch; i++;
      while (i < src.length) { if (src[i] === '\\') { i += 2; continue; } if (src[i] === q) { i++; break; } i++; }
      pendingIdent = '';
      continue;
    }
    if (ch === '{' || ch === '[' || ch === '(') { depth++; i++; pendingIdent = ''; continue; }
    if (ch === ']' || ch === ')') { depth--; i++; pendingIdent = ''; continue; }
    if (ch === '}') { if (depth === 0) break; depth--; i++; pendingIdent = ''; continue; }
    if (depth === 0) {
      if (/[A-Za-z_$]/.test(ch)) { let j = i; let id = ''; while (j < src.length && /[\w$]/.test(src[j])) { id += src[j]; j++; } pendingIdent = id; i = j; continue; }
      if (ch === ':' && pendingIdent) { keys.add(pendingIdent); pendingIdent = ''; i++; continue; }
      if (!/\s/.test(ch)) pendingIdent = '';
    }
    i++;
  }
  return keys;
}

function checkPackParity(file, src, koName, enName) {
  const ko = packKeys(src, koName);
  const en = packKeys(src, enName);
  if (!ko) return fail(file, `missing ${koName} pack`);
  if (!en) return fail(file, `missing ${enName} pack`);
  for (const k of ko) if (!en.has(k)) fail(file, `${enName} missing key '${k}' (present in ${koName})`);
  for (const k of en) if (!ko.has(k)) fail(file, `${koName} missing key '${k}' (present in ${enName})`);
}

// Every "label: '...korean...'" inside an option array must have a labelEn nearby.
function checkOptionLabels(file, src) {
  const re = /\blabel:\s*'[^']*[가-힣][^']*'/g;
  let m;
  while ((m = re.exec(src))) {
    const tail = src.slice(m.index, m.index + 220);
    if (!/labelEn\s*:/.test(tail)) {
      const line = src.slice(0, m.index).split('\n').length;
      fail(file, `option label without labelEn near line ${line}: ${m[0].slice(0, 60)}`);
    }
  }
}

// Korean inside a literal HTML attribute value (not an interpolated expression).
function checkAttrKorean(file, src) {
  const re = /(aria-label|title|placeholder)="([^"]*)"/g;
  let m;
  while ((m = re.exec(src))) {
    if (KO.test(m[2])) {
      const line = src.slice(0, m.index).split('\n').length;
      fail(file, `hardcoded Korean in ${m[1]} attribute (line ${line}): ${m[2].slice(0, 50)}`);
    }
  }
}

const targets = [
  { file: 'assets/js/f4-route-guide.js', packs: [['STR_KO', 'STR_EN'], ['TAB_LABEL_KO', 'TAB_LABEL_EN']] },
  { file: 'assets/js/short-stay-checker.js', packs: [['STR_KO', 'STR_EN']] },
];

for (const t of targets) {
  const abs = path.join(repoRoot, t.file);
  if (!fs.existsSync(abs)) { fail(t.file, 'file not found'); continue; }
  const src = fs.readFileSync(abs, 'utf8');
  for (const [ko, en] of t.packs) checkPackParity(t.file, src, ko, en);
  checkOptionLabels(t.file, src);
  checkAttrKorean(t.file, src);
}

if (problems.length) {
  console.error('[check_popup_i18n] popup chrome i18n problems:');
  problems.forEach((p) => console.error(`- ${p}`));
  process.exit(1);
}

console.log('[check_popup_i18n] OK — popup chrome packs paired (ko/en), option labels carry labelEn, no Korean in attribute literals');
