#!/usr/bin/env node
/*
 * check_employment_analyzer_modes.mjs
 * ----------------------------------------------------------------------------
 * Mode-suite regression for the upgraded employment analyzer
 * (field_labor / professional / service / arts_entertainment / ambiguous).
 *
 * Suites are generated by scripts/build_employment_test_cases.mjs.
 *
 * HARD invariants (any failure → exit 1):
 *   - NO HALLUCINATED CODE: every candidate code exists in jobcode_master.json
 *     with the matching classification type.
 *   - tracks separated (occupation vs industry never leak).
 *   - sourceNotes present.
 *   - base legal caveat present (legality never implied).
 *   - expectMode matches (when asserted).
 *   - expectSignals: parsedSignals carries >=1 of the named kinds (field cases).
 *   - expectLegalSensitivity / expectMaxConfidence / expectWarningIncludes /
 *     clarificationRequired (when asserted).
 *   - neverSilentDeadEnd: candidates OR (interpretation + clarification).
 *
 * SOFT quality gate (cluster coverage): expectOccupationCluster /
 * expectIndustryCluster keywords should appear in a candidate (or the code is
 * legitimately withheld + clarification required). The AGGREGATE hit rate must
 * stay above MIN_CLUSTER_HIT_RATE so coverage cannot silently regress.
 *
 * Run:  node scripts/check_employment_analyzer_modes.mjs
 * ----------------------------------------------------------------------------
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createEmploymentAnalyzer } from './employment_code_analyzer.mjs';
import { loadEmploymentAnalyzerDeps } from './employment_data_loader.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const readJson = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));

const SUITES = [
  'field_labor_test_cases.json',
  'professional_test_cases.json',
  'service_test_cases.json',
  'arts_entertainment_test_cases.json',
  'ambiguous_test_cases.json'
];
const MIN_CLUSTER_HIT_RATE = 0.8;
const MIN_MODE_PRECISION = 0.7;
const MIN_COUNTS = {
  field_labor_test_cases: 150, professional_test_cases: 100, service_test_cases: 80,
  arts_entertainment_test_cases: 60, ambiguous_test_cases: 60
};
// service and professional share a fuzzy boundary (a cafe manager is both); a
// mismatch BETWEEN them is tolerated. ambiguous_mode is always an acceptable,
// honest fallback. But field_labor and arts_entertainment must be detected
// (and never spuriously triggered), so those mismatches are hard failures.
const SOFT_PAIR = new Set(['service_mode', 'professional_mode']);
function modeOutcome(expected, actual) {
  if (actual === expected) return 'exact';
  if (actual === 'ambiguous_mode') return 'fallback';          // honest "not sure"
  if (SOFT_PAIR.has(expected) && SOFT_PAIR.has(actual)) return 'soft'; // svc<->pro
  return 'hard';                                                // confidently wrong
}

const deps = loadEmploymentAnalyzerDeps();
const analyzer = createEmploymentAnalyzer(deps);
const validCodes = { occupation: new Set(), industry: new Set() };
for (const r of deps.data.data) validCodes[r.type] && validCodes[r.type].add(String(r.code));

const CONF = { low: 0, medium: 1, high: 2 };
let failures = 0, total = 0;
let clusterChecks = 0, clusterHits = 0;
let modeAsserts = 0, modeExact = 0;
const fail = (id, msg) => { failures++; console.error(`  ✗ [${id}] ${msg}`); };
const includesIn = (cands, needle) =>
  cands.some((c) => (c.name && c.name.includes(needle)) || (c.path && c.path.includes(needle)) || (c.officialName && c.officialName.includes(needle)));

for (const suiteFile of SUITES) {
  const suite = readJson(`data/employment/${suiteFile}`);
  const key = suiteFile.replace('.json', '');
  if (MIN_COUNTS[key] && suite.cases.length < MIN_COUNTS[key])
    fail(key, `suite too small: ${suite.cases.length} < required ${MIN_COUNTS[key]}`);

  for (const tc of suite.cases) {
    total++;
    const res = analyzer.analyze({ text: tc.input, locale: tc.language === 'en' ? 'en' : (tc.language === 'ko' ? 'ko' : undefined) });
    const occ = res.occupationCandidates, ind = res.industryCandidates;
    const all = [...occ, ...ind];

    // --- HARD: no hallucinated codes + track separation ---
    for (const c of occ) {
      if (c.classification !== 'occupation') fail(tc.id, `occ candidate wrong type ${c.classification}`);
      if (!validCodes.occupation.has(String(c.code))) fail(tc.id, `HALLUCINATED occupation code ${c.code} (${c.officialName})`);
    }
    for (const c of ind) {
      if (c.classification !== 'industry') fail(tc.id, `ind candidate wrong type ${c.classification}`);
      if (!validCodes.industry.has(String(c.code))) fail(tc.id, `HALLUCINATED industry code ${c.code} (${c.officialName})`);
    }
    // --- HARD: source metadata + legality never implied ---
    if (!Array.isArray(res.sourceNotes) || !res.sourceNotes.length) fail(tc.id, 'sourceNotes missing');
    if (!res.warnings.some((w) => w.includes('별도 확인'))) fail(tc.id, 'base legal caveat missing');
    // --- HARD: income reporting note always present ---
    if (!res.incomeReportingNote) fail(tc.id, 'incomeReportingNote missing');

    // --- mode: hard only for confident-wrong (field/arts must be exact); svc<->pro
    //     and ambiguous fallback tolerated, with an aggregate precision gate. ---
    if (tc.expectMode) {
      modeAsserts++;
      const outcome = modeOutcome(tc.expectMode, res.mode);
      if (outcome === 'exact') modeExact++;
      else if (outcome === 'hard') fail(tc.id, `mode ${tc.expectMode} → ${res.mode} (confidently wrong) "${tc.input}"`);
    }

    // --- HARD: expected parsed signals (field cases) ---
    if (Array.isArray(tc.expectSignals) && tc.expectSignals.length) {
      const has = tc.expectSignals.some((k) => Array.isArray(res.parsedSignals[k]) && res.parsedSignals[k].length);
      if (!has) fail(tc.id, `expected parsedSignals among [${tc.expectSignals}], got none ("${tc.input}")`);
    }
    // --- HARD: legal sensitivity / confidence ceiling / warning text ---
    if (tc.expectLegalSensitivity && !(res.extracted.legalSensitivity || []).includes(tc.expectLegalSensitivity))
      fail(tc.id, `expected legalSensitivity ${tc.expectLegalSensitivity}, got ${JSON.stringify(res.extracted.legalSensitivity)}`);
    if (tc.expectMaxConfidence) {
      const cap = CONF[tc.expectMaxConfidence];
      const over = all.filter((c) => CONF[c.confidence] > cap);
      if (over.length) fail(tc.id, `confidence above ${tc.expectMaxConfidence}: ${over.map((c) => c.code + '=' + c.confidence).join(', ')}`);
    }
    if (tc.expectWarningIncludes && !res.warnings.some((w) => w.includes(tc.expectWarningIncludes)))
      fail(tc.id, `warnings missing "${tc.expectWarningIncludes}"`);
    if (tc.clarificationRequired === true && !res.clarificationRequired)
      fail(tc.id, 'expected clarificationRequired=true');

    // --- HARD: never a silent dead-end ---
    if (tc.neverSilentDeadEnd || true) {
      const understood = all.length > 0 || (res.noOfficialCodeFound && (res.parsedInterpretation || res.clarificationRequired || res.ambiguityQuestions.length));
      if (!understood) fail(tc.id, `silent dead-end (no candidates, no interpretation, no clarification) for "${tc.input}"`);
    }

    // --- SOFT: cluster coverage (aggregate gate) ---
    for (const [needle, cands, withheldOk] of [
      [tc.expectOccupationCluster, occ, occ.length === 0],
      [tc.expectIndustryCluster, ind, ind.length === 0]
    ]) {
      if (!needle) continue;
      clusterChecks++;
      const hit = includesIn(cands, needle) ||
        (tc.withholdCodeIfUnverified && withheldOk && res.clarificationRequired);
      if (hit) clusterHits++;
    }
  }
}

const rate = clusterChecks ? clusterHits / clusterChecks : 1;
const modePrecision = modeAsserts ? modeExact / modeAsserts : 1;
console.log(`\nMode suites: ${total} cases, ${failures} hard failure(s).`);
console.log(`Mode precision: ${modeExact}/${modeAsserts} = ${(modePrecision * 100).toFixed(1)}% exact (gate ${(MIN_MODE_PRECISION * 100)}%; svc↔pro & ambiguous-fallback tolerated).`);
console.log(`Cluster coverage: ${clusterHits}/${clusterChecks} = ${(rate * 100).toFixed(1)}% (gate ${(MIN_CLUSTER_HIT_RATE * 100)}%).`);
if (rate < MIN_CLUSTER_HIT_RATE) { console.error(`✗ cluster coverage below gate.`); failures++; }
if (modePrecision < MIN_MODE_PRECISION) { console.error(`✗ mode precision below gate.`); failures++; }
if (failures > 0) { console.error(`\nFAILED with ${failures} issue(s).`); process.exit(1); }
console.log('OK — modes correct, no hallucinated codes, tracks separated, signals/cautions/income-note present, cluster + mode-precision gates met.');
