#!/usr/bin/env python3
"""Build Paradiso job/industry-code runtime data from KSCO8 and KSIC11 sources.

Paradiso's HiKorea employment-information helper must show both:
  - 직종: 제8차 한국표준직업분류(KSCO8)
  - 업종: 제11차 한국표준산업분류(KSIC11)

Data source priority (highest → lowest):
  1. Full candidate JSON  data/generated/employment_reporting_ksco8_full_candidate.json
                          data/generated/employment_reporting_ksic11_full_candidate.json
     Generated by: python3 scripts/extract_employment_reporting_full_tables.py \
                     --ksco-text /tmp/ksco8.txt --ksic-text /tmp/ksic11.txt
     Validated in: data/employment_reporting_table_sample_validation_2026_05.json
     Row counts:   KSCO8 1999, KSIC11 2038

  2. Full candidate CSV   data/generated/employment_reporting_ksco8_full_candidate.csv
                          data/generated/employment_reporting_ksic11_full_candidate.csv
     Same extraction pipeline as (1); accepted when JSON is absent.

  3. Seed CSV (committed)  data/jobcode_master_ksco8_major_middle.csv  (major+middle only)
                           data/industrycode_master_ksic11_major.csv   (major only)
     Build-path scaffolding only. See coverage-protection guard below.

Coverage-protection guard:
  The committed data/jobcode_master.json is a full runtime dataset (3937 rows).
  A seed-only build (88 rows) must NEVER overwrite it. When full candidate files
  are absent, the default no-arg run is a no-op: it prints what it would do and
  leaves the committed file untouched. Writing seed output requires the explicit
  --allow-seed-downgrade flag (testing / fresh-checkout bootstrap only).
  A full-candidate build always writes, because it does not reduce coverage.

This script does NOT treat KSCO8/KSIC11 classification data as E-7 eligibility
screening. Classification lookup is a reporting-aid for HiKorea 취업정보 신고 only.
"""
from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]

# Seed paths (always committed)
KSCO8_SEED = REPO_ROOT / "data" / "jobcode_master_ksco8_major_middle.csv"
KSIC11_SEED = REPO_ROOT / "data" / "industrycode_master_ksic11_major.csv"

# Full candidate paths (generated by extract_employment_reporting_full_tables.py)
GENERATED = REPO_ROOT / "data" / "generated"
FULL_KSCO8_JSON = GENERATED / "employment_reporting_ksco8_full_candidate.json"
FULL_KSIC11_JSON = GENERATED / "employment_reporting_ksic11_full_candidate.json"
FULL_KSCO8_CSV = GENERATED / "employment_reporting_ksco8_full_candidate.csv"
FULL_KSIC11_CSV = GENERATED / "employment_reporting_ksic11_full_candidate.csv"

OUT_FILE = REPO_ROOT / "data" / "jobcode_master.json"

KSCO8_URL = "https://kssc.mods.go.kr:8443/ksscNew_web/kssc/common/ClassificationContent.do?gubun=1&strCategoryNameCode=002&categoryMenu=007&addGubun=no"
KSIC11_SOURCE = "[별표2-2] 한국표준산업분류 제11차 개정 해설서(신구연계표 포함).pdf"

_SEED_COLUMNS = {"code", "title_ko", "level", "parent_code"}


def load_seed_csv(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        raise FileNotFoundError(f"seed file not found: {path}")
    with path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        records = [dict(row) for row in reader]
    if set(reader.fieldnames or []) != _SEED_COLUMNS:
        raise ValueError(f"Unexpected seed columns in {path}: {reader.fieldnames}")
    if not records:
        raise ValueError(f"seed file is empty: {path}")
    return records


def load_full_candidate_json(path: Path) -> list[dict[str, str]]:
    """Load a full candidate JSON written by extract_employment_reporting_full_tables.py."""
    raw = json.loads(path.read_text(encoding="utf-8"))
    if isinstance(raw, list):
        records = raw
    elif isinstance(raw, dict) and "data" in raw:
        records = raw["data"]
    else:
        raise ValueError(f"Unrecognised full candidate JSON structure in {path}")
    if not records:
        raise ValueError(f"full candidate JSON is empty: {path}")
    for r in records[:3]:
        missing = _SEED_COLUMNS - set(r.keys())
        if missing:
            raise ValueError(f"full candidate JSON row missing keys {missing}: {r}")
    return [
        {"code": str(r["code"]), "title_ko": str(r["title_ko"]),
         "level": str(r["level"]), "parent_code": str(r.get("parent_code") or "")}
        for r in records
    ]


def load_full_candidate_csv(path: Path) -> list[dict[str, str]]:
    """Load a full candidate CSV written by extract_employment_reporting_full_tables.py."""
    if not path.is_file():
        raise FileNotFoundError(f"full candidate CSV not found: {path}")
    with path.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        records = [dict(row) for row in reader]
    if not records:
        raise ValueError(f"full candidate CSV is empty: {path}")
    return records


def to_runtime_rows(records: list[dict[str, str]], category: str, version_key: str) -> list[dict]:
    code_key = "직업분류판" if category == "직업" else "산업분류판"
    return [
        {
            "분류": category,
            "상세설명": row["title_ko"],
            "코드값": row["code"],
            code_key: version_key,
            "분류수준": row["level"],
            "상위코드": row["parent_code"] or None,
        }
        for row in records
    ]


def _level_set(records: list[dict[str, str]]) -> list[str]:
    seen: list[str] = []
    order = ["major", "middle", "minor", "unit", "detailed_unit"]
    present = {r["level"] for r in records}
    return [lv for lv in order if lv in present]


def build_payload(
    job_records: list[dict[str, str]],
    industry_records: list[dict[str, str]],
    data_source: str = "seed",
) -> dict:
    job_rows = to_runtime_rows(job_records, "직업", "KSCO8")
    industry_rows = to_runtime_rows(industry_records, "산업", "KSIC11")
    data = job_rows + industry_rows

    occ_levels = _level_set(job_records)
    ind_levels = _level_set(industry_records)

    if data_source == "full":
        source_label = "통계청 표준분류 전체표 기반 취업정보 신고용 직종/업종"
        coverage_note = (
            "Full candidate tables (all 5 levels). "
            "KSCO8: 1,999 rows across major/middle/minor/unit/detailed_unit. "
            "KSIC11: 2,038 rows across major/middle/minor/unit/detailed_unit. "
            "Validated 2026-05 against source PDFs."
        )
    else:
        source_label = "통계청 표준분류 기반 취업정보 신고용 직종/업종 seed"
        coverage_note = (
            "Seed data only (major+middle for KSCO8; major for KSIC11). "
            "Full 5-level extraction requires: "
            "python3 scripts/extract_employment_reporting_full_tables.py "
            "--ksco-text /tmp/ksco8.txt --ksic-text /tmp/ksic11.txt"
        )

    return {
        "source": source_label,
        "data_source": data_source,
        "source_url": KSCO8_URL,
        "source_documents": [
            "(해설서) 제8차 한국표준직업분류(공개용)_24.6.24_(최종안).pdf",
            KSIC11_SOURCE,
            "붙임 1. 외국인 취업정보 온라인 신고제 개요_수정.hwpx",
            "붙임 2. 온라인 신고 절차(관서 방문예약 시 함께 신고하는 경우).hwpx",
            "붙임 3. 온라인 신고 절차(방문예약 없이 최초 신고 또는 변경 신고하는 경우).hwpx",
            "붙임 4. 취업정보 신고 자주 묻는 질문(FAQ).docx",
        ],
        "occupation_source": {
            "classification": "제8차 한국표준직업분류",
            "announcement": "통계청 고시 제2024-328호",
            "effective_date": "2025-01-01",
            "coverage_levels": occ_levels,
            "record_count": len(job_rows),
        },
        "industry_source": {
            "classification": "제11차 한국표준산업분류",
            "announcement": "통계청 고시 제2024-2호 및 제2024-203호 부칙 개정",
            "effective_date": "2024-07-01",
            "coverage_levels": ind_levels,
            "record_count": len(industry_rows),
        },
        "employment_reporting_context": {
            "reported_fields": ["직종", "업종", "연간소득"],
            "income_bands": [
                "소득없음", "연간 1천만 원 미만", "1천만~2천만 원 미만",
                "2천만~3천만 원 미만", "3천만~4천만 원 미만",
                "4천만~5천만 원 미만", "5천만 원 이상",
            ],
            "target_statuses": [
                "E-1", "E-2", "E-3", "E-4", "E-5", "E-6", "E-7",
                "E-8", "E-9", "E-10", "F-2", "F-4", "F-6", "H-2",
                "D-7", "D-8", "D-9",
            ],
            "exclusions": ["F-5", "영리활동에 종사하지 않는 사람"],
            "deadline": "변동사항 발생일 또는 영리활동 개시일부터 15일 이내",
            "hikorea_flow_note": (
                "HiKorea 신고 화면은 직종조회와 업종조회를 별도로 선택한 뒤 "
                "연간소득 구간을 입력한다."
            ),
            "eligibility_screening_note": (
                "NOT E-7 eligibility screening. "
                "KSCO8/KSIC11 classification lookup is a reporting aid for "
                "HiKorea 취업정보 신고 only. Visa eligibility requires a "
                "separate assessment."
            ),
        },
        "coverage": {
            "note": coverage_note,
            "occupation_levels": occ_levels,
            "industry_levels": ind_levels,
        },
        "total_count": len(data),
        "categories": {"직업": len(job_rows), "산업": len(industry_rows)},
        "data": data,
    }


def _try_load_full() -> tuple[list[dict[str, str]], list[dict[str, str]]] | None:
    """Return (ksco8_records, ksic11_records) from full candidates, or None."""
    # Try JSON first
    if FULL_KSCO8_JSON.is_file() and FULL_KSIC11_JSON.is_file():
        try:
            ksco = load_full_candidate_json(FULL_KSCO8_JSON)
            ksic = load_full_candidate_json(FULL_KSIC11_JSON)
            return ksco, ksic
        except Exception as exc:
            print(f"WARNING: full candidate JSON load failed ({exc}); falling back to CSV", file=sys.stderr)
    # Try CSV
    if FULL_KSCO8_CSV.is_file() and FULL_KSIC11_CSV.is_file():
        try:
            ksco = load_full_candidate_csv(FULL_KSCO8_CSV)
            ksic = load_full_candidate_csv(FULL_KSIC11_CSV)
            return ksco, ksic
        except Exception as exc:
            print(f"WARNING: full candidate CSV load failed ({exc}); falling back to seeds", file=sys.stderr)
    return None


def main(argv: list[str] | None = None) -> int:
    argv = argv or sys.argv[1:]

    full = _try_load_full()
    if full is not None:
        job_records, industry_records = full
        data_source = "full"
        source_desc = "full candidate files (data/generated/)"
    else:
        job_records = load_seed_csv(KSCO8_SEED)
        industry_records = load_seed_csv(KSIC11_SEED)
        data_source = "seed"
        source_desc = "seed CSV files (major/middle KSCO8; major KSIC11)"

    payload = build_payload(job_records, industry_records, data_source)

    # Existing committed runtime coverage (so we never silently shrink it).
    existing_total = None
    if OUT_FILE.is_file():
        try:
            existing_total = json.loads(OUT_FILE.read_text(encoding="utf-8")).get("total_count")
        except Exception:
            existing_total = None

    if "--check" in argv:
        print(json.dumps({
            "data_source": data_source,
            "source_desc": source_desc,
            "categories": payload["categories"],
            "candidate_total": payload["total_count"],
            "committed_total": existing_total,
            "coverage": payload["coverage"],
            "full_candidate_json_present": FULL_KSCO8_JSON.is_file() and FULL_KSIC11_JSON.is_file(),
            "full_candidate_csv_present": FULL_KSCO8_CSV.is_file() and FULL_KSIC11_CSV.is_file(),
            "would_write": data_source == "full" or "--allow-seed-downgrade" in argv,
            "regenerate_full": (
                "pdftotext -layout KSCO8.pdf /tmp/ksco8.txt && "
                "pdftotext -layout KSIC11.pdf /tmp/ksic11.txt && "
                "python3 scripts/extract_employment_reporting_full_tables.py "
                "--ksco-text /tmp/ksco8.txt --ksic-text /tmp/ksic11.txt"
            ),
        }, ensure_ascii=False, indent=2))
        return 0

    # Coverage-protection guard: a seed-only build must never overwrite a
    # larger committed runtime dataset. Full candidate files are absent in
    # this branch, so the default no-arg run is a no-op that preserves the
    # existing 3937-row data/jobcode_master.json. Pass --allow-seed-downgrade
    # to deliberately write the seed output (testing / bootstrap only).
    if data_source == "seed" and "--allow-seed-downgrade" not in argv:
        if existing_total is not None and existing_total > payload["total_count"]:
            print(
                f"SKIP: full candidate files absent. Refusing to overwrite committed "
                f"runtime data (total_count={existing_total}) with seed build "
                f"(total_count={payload['total_count']}).\n"
                f"      Existing data/jobcode_master.json is left unchanged.\n"
                f"      To generate full data, run the extraction pipeline:\n"
                f"        {payload['coverage']['note']}\n"
                f"      To force a seed write anyway, pass --allow-seed-downgrade.",
                file=sys.stderr,
            )
            return 0
        # No larger committed file to protect (e.g. fresh checkout): write seed.

    OUT_FILE.parent.mkdir(exist_ok=True)
    OUT_FILE.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    occ = payload["categories"]["직업"]
    ind = payload["categories"]["산업"]
    print(f"Wrote {OUT_FILE}  [{data_source}]  직업={occ}  산업={ind}  total={occ+ind}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
